version: "3.9"

services:
  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_tdl:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
         condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000
#  bot:
#    image: helselga/diplom:$GITHUB_REF_NAME-$GITHUB_RUN_ID
#    depends_on:
#      postgres:
#        condition: service_healthy
#    volumes:
#      - ./.env:/app/.env
#    command: python manage.py runbot
  front:
    image: sermalenk/skypro-front:base
    ports:
      - 8034:80
    depends_on:
      api:
        condition: service_healthy
volumes:
  postgres_data_tdl:
