version: "3.9"

services:
  postgres:
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    image: ${DOCKERHUB_USERNAME}/diplom:master
    restart: always
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    tty: true
    healthcheck:
      test: curl -sS http://127.0.0.1:8000/ping || exit 1
      interval: 3s
      timeout: 3s
      retries: 3
  front:
    image: sermalenk/skypro-front:lesson-36
    ports:
      - 8034:80
